import { addToSyncQueue, db } from '@/lib/db'
export const RECOVERY_BACKUP_VERSION=1
const TABLES=['transactions','accounts','categories','debts','loans','financings','subscriptions','tags','contacts','budgets','goals','credit_cards','credit_invoices'] as const
type TableName=typeof TABLES[number]
export interface RecoveryBackup{format:'dfl-finance-recovery';version:number;exported_at:string;user_id:string;context:'dfl'|'personal';tables:Record<string,any[]>;counts:Record<string,number>}
export async function createRecoveryBackup(userId:string,context:'dfl'|'personal'):Promise<RecoveryBackup>{const tables:Record<string,any[]>={};const counts:Record<string,number>={};for(const n of TABLES){const rows=await(db as any)[n].where('[user_id+context]').equals([userId,context]).toArray();tables[n]=rows;counts[n]=rows.length}return{format:'dfl-finance-recovery',version:RECOVERY_BACKUP_VERSION,exported_at:new Date().toISOString(),user_id:userId,context,tables,counts}}
export function validateRecoveryBackup(value:unknown,userId:string,context:'dfl'|'personal'){const b=value as RecoveryBackup;if(!b||b.format!=='dfl-finance-recovery'||b.version!==RECOVERY_BACKUP_VERSION)throw new Error('Backup incompatível.');if(b.user_id!==userId)throw new Error('Este backup pertence a outro usuário.');if(b.context!==context)throw new Error('Este backup pertence a outro contexto.');for(const n of TABLES){if(!Array.isArray(b.tables?.[n]))throw new Error(`Backup inválido: ${n}.`);for(const r of b.tables[n])if(!r?.id||r.user_id!==userId||r.context!==context)throw new Error(`Registro inválido em ${n}.`)}return b}
export function downloadRecoveryBackup(b:RecoveryBackup,prefix='dfl-finance-backup'){if(typeof window==='undefined')return;const blob=new Blob([JSON.stringify(b,null,2)],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${prefix}-${b.context}-${b.exported_at.slice(0,19).replace(/[:T]/g,'-')}.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
export async function restoreRecoveryBackup(raw:unknown,userId:string,context:'dfl'|'personal'){const b=validateRecoveryBackup(raw,userId,context);let restored=0;for(const n of TABLES){const table=(db as any)[n];for(const original of b.tables[n]){const exists=await table.get(original.id);const record={...original,user_id:userId,context,sync_status:'pending',updated_at:new Date().toISOString()};await table.put(record);await addToSyncQueue(userId,n as TableName,exists?'update':'create',record.id,record);restored++}}return{restored,exportedAt:b.exported_at}}
