'use client'

import { useState, useEffect, useMemo } from 'react'
import { useRouter } from 'next/navigation'
import { useAuth } from '@/lib/hooks/useAuth'
import { useToast } from '@/contexts/ToastContext'
import { X, ArrowRightLeft, Wallet, Loader2, Check, ChevronRight, ArrowDown, Building2, UserRound, AlertTriangle } from 'lucide-react'
import BankLogo from '@/components/BankLogo'
import MoneyInput from '@/components/MoneyInput'
import { useAccountsList } from '@/hooks/useAccountsList'
import { useHapticFeedback } from '@/hooks/useHapticFeedback'
import { transferBetweenAccounts } from '@/lib/accountOperations'

interface TransferModalProps { isOpen:boolean; onClose:()=>void; onComplete?:()=>void; context?:'dfl'|'personal' }
const fmt=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const balanceClass=(v:any)=>Number(v||0)>0?'text-emerald-600 dark:text-emerald-400':Number(v||0)<0?'text-rose-600 dark:text-rose-400':'text-gray-400 dark:text-gray-500'

export default function TransferModal({isOpen,onClose,onComplete,context:forcedContext}:TransferModalProps){
 const router=useRouter(); const {user}=useAuth(); const {showToast}=useToast(); const {success:hapticSuccess,error:hapticError,vibrate}=useHapticFeedback()
 const [fromContext,setFromContext]=useState<'dfl'|'personal'>(forcedContext||'dfl'); const [toContext,setToContext]=useState<'dfl'|'personal'>(forcedContext||'dfl')
 const [fromAccountId,setFromAccountId]=useState(''); const [toAccountId,setToAccountId]=useState(''); const [amountNum,setAmountNum]=useState(0); const [description,setDescription]=useState(''); const [loading,setLoading]=useState(false); const [showFromAccs,setShowFromAccs]=useState(false); const [showToAccs,setShowToAccs]=useState(false); const [showZeroFrom,setShowZeroFrom]=useState(false)
 const {data:allAccounts}=useAccountsList()
 const accounts=useMemo(()=>allAccounts||[],[allAccounts])
 const fromAccounts=useMemo(()=>accounts.filter((a:any)=>a.context===fromContext).sort((a:any,b:any)=>Number(b.balance||0)-Number(a.balance||0)||(a.name||'').localeCompare(b.name||'')),[accounts,fromContext])
 const toAccounts=useMemo(()=>accounts.filter((a:any)=>a.context===toContext).sort((a:any,b:any)=>Number(b.balance||0)-Number(a.balance||0)||(a.name||'').localeCompare(b.name||'')),[accounts,toContext])
 const fromAcc=fromAccounts.find((a:any)=>a.id===fromAccountId); const toAcc=toAccounts.find((a:any)=>a.id===toAccountId)
 const projectedFrom=Number(fromAcc?.balance||0)-amountNum; const projectedTo=Number(toAcc?.balance||0)+amountNum
 const visibleFrom=fromAccounts.filter((a:any)=>showZeroFrom||Number(a.balance||0)!==0||a.id===fromAccountId)
 useEffect(()=>{if(isOpen){const c=forcedContext||'dfl';setFromContext(c);setToContext(c);setFromAccountId('');setToAccountId('');setAmountNum(0);setDescription('');setShowZeroFrom(false)}},[isOpen,forcedContext])
 async function handleTransfer(){if(!user){showToast('Usuário não autenticado.','warning');return} if(!fromAccountId||!toAccountId||amountNum<=0){showToast('Preencha origem, destino e valor.','warning');hapticError();return} if(fromAccountId===toAccountId){showToast('As contas devem ser diferentes.','warning');hapticError();return} setLoading(true);try{await transferBetweenAccounts({userId:user.id,fromAccountId,toAccountId,amount:amountNum,description});hapticSuccess();showToast(projectedFrom<0?'Transferência concluída. A conta de origem ficou negativa.':'Transferência realizada com sucesso.','success');onComplete?.();onClose();router.refresh()}catch(e:any){hapticError();showToast('Erro: '+(e?.message||'erro desconhecido'),'error')}finally{setLoading(false)}}
 if(!isOpen)return null
 const ContextToggle=({value,onChange}:{value:'dfl'|'personal';onChange:(v:'dfl'|'personal')=>void})=><div className="grid grid-cols-2 gap-1 rounded-[18px] bg-slate-100/90 p-1 dark:bg-slate-800/90">{(['dfl','personal'] as const).map(c=><button type="button" key={c} onClick={()=>{onChange(c);vibrate([8])}} className={`flex items-center justify-center gap-2 rounded-[15px] px-3 py-2.5 text-[12px] font-bold transition-all ${value===c?(c==='dfl'?'bg-slate-900 text-white shadow-sm dark:bg-slate-600':'bg-teal-600 text-white shadow-sm'):'text-slate-500 dark:text-slate-400'}`}>{c==='dfl'?<Building2 size={15}/>:<UserRound size={15}/>} {c==='dfl'?'Empresa':'Pessoal'}</button>)}</div>
 const AccountButton=({acc,placeholder,onClick}:{acc:any;placeholder:string;onClick:()=>void})=><button type="button" onClick={onClick} className="flex w-full items-center justify-between rounded-[22px] bg-slate-50 p-4 text-left transition active:scale-[.985] dark:bg-slate-800/80"><div className="flex min-w-0 items-center gap-3">{acc?<BankLogo color={acc.color} name={acc.name} size="md"/>:<div className="flex h-11 w-11 items-center justify-center rounded-[15px] bg-white shadow-sm dark:bg-slate-700"><Wallet size={20} className="text-slate-400"/></div>}<div className="min-w-0"><p className={`truncate text-[15px] font-bold ${acc?'text-slate-900 dark:text-white':'text-slate-400'}`}>{acc?.name||placeholder}</p>{acc&&<p className={`mt-0.5 text-[12px] font-bold tabular-nums ${balanceClass(acc.balance)}`}>Saldo {fmt(acc.balance)}</p>}</div></div><ChevronRight size={18} className="shrink-0 text-slate-400"/></button>
 const AccountSheet=({open,close,title,items,selected,onSelect,origin=false}:{open:boolean;close:()=>void;title:string;items:any[];selected:string;onSelect:(id:string)=>void;origin?:boolean})=>open?<div className="fixed inset-0 z-[170] flex items-end justify-center" onClick={close}><div className="app-overlay absolute"/><div className="app-sheet-panel z-10 max-h-[72dvh] max-w-md overflow-y-auto p-6" onClick={e=>e.stopPropagation()}><div className="sticky top-0 z-10 -mx-1 mb-4 flex items-center justify-between bg-white/95 px-1 py-2 backdrop-blur dark:bg-slate-900/95"><div><h3 className="text-xl font-bold text-slate-900 dark:text-white">{title}</h3><p className="mt-1 text-[12px] text-slate-400">{origin?'Contas com saldo aparecem primeiro.':'Escolha onde o valor será recebido.'}</p></div><button type="button" onClick={close} className="app-icon-action"><X size={19}/></button></div><div className="space-y-2">{items.map((acc:any)=><button type="button" key={acc.id} onClick={()=>{onSelect(acc.id);close();vibrate([8])}} className={`flex w-full items-center gap-3 rounded-[20px] p-3.5 text-left transition active:scale-[.985] ${acc.id===selected?'bg-teal-50 ring-1 ring-teal-500/20 dark:bg-teal-500/10':'bg-slate-50 dark:bg-slate-800/60'}`}><BankLogo color={acc.color} name={acc.name} size="md"/><div className="min-w-0 flex-1"><p className="truncate text-[15px] font-bold text-slate-900 dark:text-white">{acc.name}</p><p className={`mt-0.5 text-[12px] font-bold tabular-nums ${balanceClass(acc.balance)}`}>{fmt(acc.balance)}</p></div>{acc.id===selected&&<Check size={20} className="text-teal-500"/>}</button>)}{origin&&!showZeroFrom&&fromAccounts.some((a:any)=>Number(a.balance||0)===0)&&<button type="button" onClick={()=>setShowZeroFrom(true)} className="w-full rounded-[18px] px-4 py-3 text-[12px] font-bold text-slate-500 dark:text-slate-400">Mostrar contas com saldo zerado</button>}</div></div></div>:null
 return <div className="fixed inset-0 z-[150] flex items-end justify-center" onClick={onClose}><div className="app-overlay absolute"/><div className="app-sheet-panel z-10 max-h-[92dvh] max-w-md overflow-y-auto p-6 pb-[max(1.5rem,var(--safe-area-bottom))]" onClick={e=>e.stopPropagation()}><div className="mx-auto mb-6 h-1.5 w-12 rounded-full bg-slate-300 dark:bg-slate-700"/><div className="mb-6 flex items-center justify-between"><div><h2 className="text-[20px] font-bold text-slate-900 dark:text-white">Transferência rápida</h2><p className="mt-1 text-[12px] text-slate-400">Veja o saldo antes e depois de confirmar.</p></div><button type="button" onClick={onClose} className="app-icon-action"><X size={20}/></button></div>
 <section className="space-y-3"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-slate-400">Conta de origem</p><ContextToggle value={fromContext} onChange={v=>{setFromContext(v);setFromAccountId('')}}/><AccountButton acc={fromAcc} placeholder="Selecionar conta de saída" onClick={()=>setShowFromAccs(true)}/></section>
 <div className="my-4 flex justify-center"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-teal-500/10 text-teal-500"><ArrowDown size={20}/></div></div>
 <section className="space-y-3"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-slate-400">Conta de destino</p><ContextToggle value={toContext} onChange={v=>{setToContext(v);setToAccountId('')}}/><AccountButton acc={toAcc} placeholder="Selecionar conta de entrada" onClick={()=>setShowToAccs(true)}/></section>
 <section className="mt-7"><p className="mb-3 text-[10px] font-bold uppercase tracking-[.12em] text-slate-400">Valor a transferir</p><div className="flex items-center gap-2 rounded-[22px] bg-slate-50 px-5 py-4 dark:bg-slate-800/80"><span className="text-[20px] font-medium text-slate-400">R$</span><MoneyInput value={amountNum} onChange={n=>setAmountNum(Number(n)||0)} ariaLabel="Valor da transferência" selectOnFocus className="w-full bg-transparent text-[32px] font-black tabular-nums text-slate-900 dark:text-white"/></div>{fromAcc&&amountNum>0&&<div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-[18px] bg-rose-500/5 p-3"><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Origem após</p><p className={`mt-1 text-[14px] font-black tabular-nums ${balanceClass(projectedFrom)}`}>{fmt(projectedFrom)}</p></div><div className="rounded-[18px] bg-emerald-500/5 p-3"><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Destino após</p><p className={`mt-1 text-[14px] font-black tabular-nums ${balanceClass(projectedTo)}`}>{toAcc?fmt(projectedTo):'Selecione'}</p></div></div>}{fromAcc&&amountNum>0&&projectedFrom<0&&<div className="mt-3 flex gap-2 rounded-[18px] bg-amber-500/10 p-3 text-[12px] font-semibold text-amber-700 dark:text-amber-300"><AlertTriangle size={17} className="shrink-0"/>A transferência é permitida, mas a origem ficará negativa em {fmt(projectedFrom)}.</div>}</section>
 <section className="mt-5"><p className="mb-3 text-[10px] font-bold uppercase tracking-[.12em] text-slate-400">Descrição opcional</p><input data-premium-input="true" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Ex.: repasse para iFood Pago" className="w-full rounded-[22px] bg-slate-50 px-5 py-4 text-[15px] font-semibold text-slate-900 outline-none dark:bg-slate-800/80 dark:text-white"/></section>
 <button type="button" onClick={()=>{vibrate([10,50]);handleTransfer()}} disabled={loading||!fromAccountId||!toAccountId||amountNum<=0} className="mt-7 flex w-full items-center justify-center gap-2 rounded-[24px] bg-teal-600 py-4 text-[15px] font-bold text-white shadow-lg shadow-teal-600/15 transition active:scale-[.985] disabled:opacity-40">{loading?<Loader2 size={22} className="animate-spin"/>:<><ArrowRightLeft size={19}/>Transferir agora</>}</button>
 <AccountSheet open={showFromAccs} close={()=>setShowFromAccs(false)} title="Conta de origem" items={visibleFrom} selected={fromAccountId} onSelect={setFromAccountId} origin/><AccountSheet open={showToAccs} close={()=>setShowToAccs(false)} title="Conta de destino" items={toAccounts.filter((a:any)=>a.id!==fromAccountId)} selected={toAccountId} onSelect={setToAccountId}/></div></div>
}
